create table IF NOT EXISTS coffee
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cup_size BIGINT NOT NULL,
    milk_size BIGINT NOT NULL,
    sugar_size BIGINT NOT NULL,
    water_size BIGINT NOT NULL,
    coffee_type CHARACTER VARYING(20) NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_coffee PRIMARY KEY (id)
)

